project:
  type: website
  output-dir: docs

website:
  title: "Zachary Cramton"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: file/path/to/sp-25.resume.pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

