project:
  type: website
  output-dir: docs

website:
  title: "Zachary Cramton Personal Site"
  favicon: media/cauliflower.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: media/sp-25-resume.pdf
        text: Resume
  page-footer:
    background: light
    left: Copyright 2025, Zachary Cramton
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/zcramton/zcramton.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}.


format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

editor: visual

