project:
  type: website
  output-dir: docs
  resources:
    - media/

website:
  title: "Zachary Cramton"
  favicon: media/favicon.svg
  navbar:
    title: "ZC"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Portfolio
      - href: writing.qmd
        text: Writing
      - href: media/cramtonz_resume_sp26.pdf
        text: Resume
        target: _blank
  page-footer:
    background: light
    left: "©2026 Zachary Cramton"
    right: "Built with [{{< fa brands github >}}](https://docs.github.com/en/pages){target=_blank} and [Quarto](https://quarto.org/){target=_blank}"

format:
  html:
    theme:
      - sandstone
      - style.scss
    toc: false

editor: visual
