---
title: "Projects"
toc: true
---
## 2026

####  Personal Work

This year I aim to complete several white papers and grey reports on a variety of topics in urban and environmental planning. These topics include:
- Light Truck Size and Emissions Policy; Impacts on Urban Form
- Protecting Drivers Over Pedestrians; Discrepancies in Infrastructure and Vehicle Policy
- E-Bike Regulation, Enforcement, and Policy
- Network Analysis of Walkable, Livable Cities

I also plan to start development of a water efficient press-down bottle sprayer for cleaning bottles before reuse or recycling.

### Spring 2026

#### Public Communication for Natural Resources - NR400

This course expands on my experience from Summer 2025 and further examines communication for non-expert audiences through the lens of bias, clarity, and multi-media communication.

#### ESS Capstone - ESS 440

Like senior design this course provides an opportunity to apply skills to real world problems. My group will be exploring the NASA GLOBE Observer data and working with CitSci to pilot data system redundancy options and create local support for misquito habitat reporting in the City of Fort Collins.

## 2025
### Fall 2025

#### ESS Independent Study - ESS 495

Throughout 2025, I spearheaded a project to modernize the Alternative Transportation Fee Advisory Board website and rebuild records from the ten years since the board's inception. This included historical archival work, database management, web design, and financial record keeping culminating in a knowledge database to preserve the boards institutional knowledge and precedent for future years. You can find the website at [atfab.colostate.edu](https://atfab.colostate.edu){target="_blank"}.

#### Earth Systems Ecology - ESS 411

This course examined ecology from a systems perspective exploring earth cycles and their impact on the climate. Throughout this course I completed logic models, and prepared a draft for the NSF Graduate Research Fellowship Program (GRFP) application. The practice with systems thinking and synthesizing ecological concepts was helpful but the experience of drafting a application to the NSF-GRFP was novel and incredibly informative.

### Summer 2025

#### Writing in the Disciplines: Sciences - CO 301B

This course provided a fresh prospective on academic writing focusing on scientific communication for non-expert audiences. I wrote two articles in the style of the Scientific American. 

- [Concrete Jungles: Affulence and Environmental Health in American Cities](media/co301b_schell_advance.pdf){target="_blank"} is an advance discussing Schell et al. 2020 and the implications of historical planning discrimination on current urban ecological health.
- [Seeing Cities Clearly: How AI and Drones Are Rewriting the Urban Map](media/co301b_urbanDroneMapping_feature.pdf){target="_blank"} is a feature length article discussing opportunities for drones and AI modeling to improve efficiency in urban and regional planning.

### Spring 2025

#### Quantitative Reasoning for Ecosystem Science- ESS 330

In the spring of 2025 I took a class on quantitative reasoning based in R. The course focused on applying instruction on coding in R to applications in statistics and data science. I found this class to be one of my most valuable classes so far, giving me a solid base of knowledge for future coding, web design and data analytics projects.

##### [Building a personal website:](https://zachary.cramton.com){target="_blank"}

-   For this class I built a personal website with Github Pages.
-   Created and managed a github repo for access to all the code.
-   Began reformatting file management across my personal systems.
-   Involved extensive troubleshooting and became familiar with R and Terminal syntax.

##### Coursework:

The rest of the work completed for this class can be found on the github pages site I created for the coursework. It can be found on [this site](https://zachary.cramton.com/csu_ess_330/){target="_blank"} also built with Github Pages.

#### Sustainability Science - ESS 312

In this course I conducted a research project exploring impacts and perceptions the Starship food delivery robots used by Grubhub to deliver food from the dining halls and student center around campus. This research conducted throughout the 2025 Spring semester, interviewed students, staff, and faculty in the Warner College of Natural Resources to collect initial impressions of the Starship robots in the months after their January 2025 introduction. 

This report collected words and phrases for future Q-methodology research in addition to forming a baseline understanding of opinions of within the College of Natural Resources. Our research showed, at best, neutral feeling regarding the food delivery robots with negative undertones. Most of the negative feedback related to questions of inefficient spending, more traffic and obstacles on the sidewalks and at intersections as well as a general lack of need.

<a href="media/ess312_final_report.pdf" target="_blank"> CSU Food Delivery Robots Final Report </a>

#### Life Cycle Assessment for Sustainability - ESS 555

In this course I completed a comparative LCA assessing the sustainability of two liquid hand soap packaging options. The project was conducted in three main phases: 

- [Goal & Scope Report](media/ess555_g+s_report.pdf){target="_blank"} 
- [Life Cycle Inventory Report](media/ess555_lci_report.pdf){target="_blank"} 
- [Life Cycle Impact Assessment](media/ess555_final_report.pdf){target="_blank"}

The comparative LCA resulted in mixed impacts between conventional PET bottles with PP caps and composite laminate pouches. That said, my assessment did not align with the claims of significant sustainability improvements made by refill pouch manufacturers based on my predefined system assumptions and constraints. This result may differ in a different scenario, particularly with a more complex logistics system. Throughout the course, I learned how to use OpenLCA and conduct life cycle assessments including sourcing data and defining parameters for the assessment.

## 2024
### Fall 2024

#### Watershed Sustainability - WR204

In the fall of 2024 I took a class on watershed science. The final project was a collaborative river reach assessment based on data released by the City of Fort Collins.

<a href="media/wr204_poudre_river_reach_assessment.pdf" target="_blank"> Poudre River Reach Assessment </a>
